version: '3'

services:

  nginx:
    build: ./docker/nginx
    container_name: "${CURRDIR}_web"
    ports:
      - '80:80'
    depends_on:
      - php
    volumes:
      - .:/var/www/html
      - "../FDM-netaxept:/var/www/FDM-netaxept"

  php:
    build: ./docker/php
    container_name: "${CURRDIR}_php"
    environment:
      PHP_IDE_CONFIG: serverName=Docker
    volumes:
      - .:/var/www/html
      - "../FDM-netaxept:/var/www/FDM-netaxept"
